### ISSUE TITLE
mix_odd_gamma bug

### ISSUE THREAD

**Issue by Lysxia** [janestreet/splittable_random#1]
The `mix_odd_gamma` function should "fix" its result if the popcount is too low, but in its current version it is doing the opposite.

https://github.com/janestreet/splittable_random/blob/12be9d6c2ea8abdf9bf40824d14ada0043022f60/src/splittable_random.ml#L61-L64

This is a bug inherited from a typo in the code of the original SplitMix paper. The text gives the correct interpretation:

> Therefore we require that the number of such pairs, as computed by `Long.bitCount(z ^ (z >>> 1))`, exceed `24`; if it does not, then the candidate `z` is replaced by the `XOR` of `z` and `0xaaaaaaaaaaaaaaaaL`

I found that in this blogpost: http://www.pcg-random.org/posts/bugs-in-splitmix.html

**Comment by hhugo** [comment]
Thanks for the report. We'll push a fix soon.
